### ISSUE TITLE
CFOG_sar = torch.mul(CFOG(i), z) 

### ISSUE THREAD

**Issue by zhangjianhhy** [yeyuanxin110/MU-Net#1]
叶老师您好！感谢您分享您的代码！我在学习您代码的过程中遇到一些困惑，看到有这样一行‘’ CFOG_sar = torch.mul(CFOG(i), z) ‘’，其中CFOG(i)出来后是8通道的，且这8通道的相加后每个地方都变成了1。请问这个CFOG(i)出来的是图像i的CFOG描述符吗？期待您的回答！

**Comment by Henryrjh** [comment]
> 叶老师您好！感谢您分享您的代码！我在学习您代码的过程中遇到一些困惑，看到有这样一行‘’ CFOG_sar = torch.mul(CFOG(i), z) ‘’，其中CFOG(i)出来后是8通道的，且这8通道的相加后每个地方都变成了1。请问这个CFOG(i)出来的是图像i的CFOG描述符吗？期待您的回答！

您好，请问您能正常运行demo吗？我的提示没有找到CFOG模块。

**Comment by Ym1314520** [comment]
我也没有找到CFOG模块，请问楼主如何解决的？

**Comment by yeyuanxin110** [comment]
唐腾峰: 你回答一下这个问题哈













--

Yuanxin YE（叶沅鑫）
PhD,  Professor (博士，教授，博导）

Facultyof Geosciences and Enviromental Engineering (地球科学与环境工程学院)
Southwest Jiaotong University（西南交通大学）








在 2024-04-30 14:15:43，"Doc.Ym" ***@***.***> 写道：

我也没有找到CFOG模块，请问楼主如何解决的？

**Comment by long123524** [comment]
> > 叶老师您好！感谢您分享您的代码！我在学习您代码的过程中遇到一些困惑，看到有这样一行‘’ CFOG_sar = torch.mul(CFOG(i), z) ‘’，其中CFOG(i)出来后是8通道的，且这8通道的相加后每个地方都变成了1。请问这个CFOG(i)出来的是图像i的CFOG描述符吗？期待您的回答！
> 
> 您好，请问您能正常运行demo吗？我的提示没有找到CFOG模块。

我也有同样的问题，楼主怎么解决的？
